steps:

- id: 'Exec unit tests'
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: 
    - 'PROJECT_ROOT=./src/sum'

- id: 'Build project'
  name: 'gcr.io/cloud-builders/go'
  args: ['build', 'app.go']
  env: 
    - 'PROJECT_ROOT=./src/sum'

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fullcycle-go-ci', '.']

images: ['gcr.io/$PROJECT_ID/fullcycle-go-ci']