steps:

- id: 'Exec unit tests'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'sum']
  env: 
    - 'GOPATH=.'

- id: 'Build project'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'sum']
  env: 
    - 'GOPATH=.'

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fullcycle-go-ci', '.']

images: ['gcr.io/$PROJECT_ID/fullcycle-go-ci']